name: demoproject_with_get_x
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  cloud_firestore: ^3.4.8
  firebase_auth: ^3.9.0
  firebase_storage: ^10.3.8
  firebase_database: ^9.1.4
  get: 4.6.5
  google_sign_in: '^4.5.1'
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/grp.png
    - assets/images/edit.png
    - assets/images/search.png
    - assets/images/call.png
    - assets/images/cam.png
    - assets/images/msg.png
    - assets/images/ellipse.png
  uses-material-design: true

