// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApRY18o_BjMEDe5em1ZC7oGlmKB0OZEfk',
    appId: '1:963897153700:android:523296ba9021376a14ae31',
    messagingSenderId: '963897153700',
    projectId: 'project-demo-firebase-2c5f7',
    databaseURL: 'https://project-demo-firebase-2c5f7-default-rtdb.firebaseio.com',
    storageBucket: 'project-demo-firebase-2c5f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQWyvuUmfvpjLr-AnCWGraNA9GKRXdaMQ',
    appId: '1:963897153700:ios:e37c891762f23eda14ae31',
    messagingSenderId: '963897153700',
    projectId: 'project-demo-firebase-2c5f7',
    databaseURL: 'https://project-demo-firebase-2c5f7-default-rtdb.firebaseio.com',
    storageBucket: 'project-demo-firebase-2c5f7.appspot.com',
    iosClientId: '963897153700-17m79l3l1j73pir2c7923873gnnkfa33.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoprojectWithGetx',
  );
}
